### ISSUE TITLE
Atlantis alternative

### ISSUE THREAD

**Issue by ZIJ** [bilenkis/terraform-provider-metabase#1]
Hi Yuri, I tried to reach out to you via other channels but failed so couldn't think of anything better than raising an issue in one of your projects

Basically, I stumbled upon that [post](https://tech.deliveryhero.com/a-week-in-the-life-of-a-principal-engineer/) in Delivery Hero's engineering blog; it mentions that the team were considering Atlantis to automate K8S upgrades. And also noticed that you guys forked Atlantis.

We are building a modern open-source alternative to Atlantis, [Digger](github.com/diggerhq/digger). Quite early so I wanted to reach out to you to learn more about the way you guys are using Atlantis, painpoints if any, etc

Would you be open to that?

**Comment by bilenkis** [comment]
Hey @ZIJ, thank you for reaching me out. The project looks very promising. However, we're pretty happy with Atlantis atm. We'll keep Digger on our radar if we face with any troubles we cannot manage with the current setup.
